rootProject.name = "cloudstream-extensions"

include(":Anichin")
include(":Donghub")
include(":Pencurimovie")
include(":Anoboy")
include(":Lk21")
include(":Donghuastream")
include(":Ngefilm")
include(":Otakudesu")
include(":Samehadaku")
include(":Animexin")
include(":Klikxxi")
include(":Dutafilm")
include(":Moviesmod")
